### ISSUE TITLE
Incluir en el Readme los miembros del equipo

### ISSUE THREAD

**Issue by HugoLebredo** [Arquisoft/dede_es5a#1]
En el archivo Readme.md  del repositorio es debe crearse una sección llamada **Miembros del equipo**  en la que cada integrante realice un commit que incluya 2 cosas:

- Nombre completo
- UO

**Comment by uo276406** [comment]
He creado la sección y he añadido mis datos :)

**Comment by SofiaYYQ** [comment]
Todos los nombre y UOs están añadidos. [Haz click aquí para verlo](https://github.com/Arquisoft/dede_es5a).
