### ISSUE TITLE
Ver vídeo de pautas para diagramas

### ISSUE THREAD

**Issue by UO250825** [Arquisoft/dede_es5a#11]
[Enlace a Youtube](https://www.youtube.com/watch?v=wgpSdpny-0c)

**Comment by uo276406** [comment]
Dejo un resumen para cuando hagamos los diagramas tenerlo en cuenta:
- Títulos cortos y concisos
- Flechas unidireccionales con descripciones
- Consistencia en las formas (cajas de diagramas de tamaños iguales en general)
- Evitar colores quepuedan confundirse si se imprime a blanco y negro o daltonismo
- Orientación y posicionamiento importante
- Leyenda

**Comment by SofiaYYQ** [comment]
- Evitar acrónimos que no son conocidos por todos los stakeholders.
