### ISSUE TITLE
Creación de un CRUD de centros de distribución

### ISSUE THREAD

**Issue by uo276406** [Arquisoft/dede_es5a#112]
Se deberá crear un CRUD de centros de dsitribució para poder mostrar posteriormente un mapa con estos, añadirlos por un adminstrador entre otras opciones varias... Los centros de distribución tendrán los campos name, longitude, latitude... Es posible que el usuario adminstrador añada la dirección y la aplicación calcule las coordenadas siendo esto lo que almacene en la base de datos...

**Comment by uo276406** [comment]
Puede existir de la posibilidad que se retornen los centros de distribución junto con un mapa que los ubique y sea amigable para el usuario

**Comment by SofiaYYQ** [comment]
> Puede existir de la posibilidad que se retornen los centros de distribución junto con un mapa que los ubique y sea amigable para el usuario

Sí, me parece muy bien. Y cómo obtenemos el mapa desde el frontend? Con los endpoints de siempre?

**Comment by uo276406** [comment]
> > Puede existir de la posibilidad que se retornen los centros de distribución junto con un mapa que los ubique y sea amigable para el usuario
> 
> Sí, me parece muy bien. Y cómo obtenemos el mapa desde el frontend? Con los endpoints de siempre?

@SofiaYYQ Con mapbox es bastante sencillo obtener una imagen con diferentes chinchetas que indican los puntos del mapa. Al final lo que tendríais vostros es una imagen que será una url que se puede poner por ejemplo en el atributo src de una etiqueta <img>

**Comment by uo276406** [comment]
Además también hay la posiilidad de tener mapas interactivos que te permiten moverte por ellos. Tendría que investigarlo pero con mapbox es relativamente sencillo 😅

**Comment by SofiaYYQ** [comment]
hmm, vale, genial, y yo creo que un mapa interactivo molaría más aún 😃 . Aunque la respuesta puede que no sea tan rápida para el usuario a la hora de interactuar con el mapa🤔.
