### ISSUE TITLE
Creación de tests e2e

### ISSUE THREAD

**Issue by uo276406** [Arquisoft/dede_es5a#123]
Se deben crear los tests e2e en el directorio webapp/e2e, se deben crear tests para cubrir al menos un 30% del proyecto.

**Comment by SofiaYYQ** [comment]
Los tests e2e no son los de aceptación🤔? Que los de aceptación creo que no hay que hacerlos aún para esta entrega. Pero sí que podemos hacer uno para ver que pasa el e2etest en el despliegue.

**Comment by uo276406** [comment]
> Los tests e2e no son los de aceptación🤔? Que los de aceptación creo que no hay que hacerlos aún para esta entrega. Pero sí que podemos hacer uno para ver que pasa el e2etest en el despliegue.

mmmm... Si lo acabo de mirar, no son necesarios, pero estaría bien hacer uno para probar el despliegue 😅

**Comment by uo276406** [comment]
Voy a intentar hacer uno para ver si me pasa el despliegue o no que quiero saber si funciona o no en Azure. Gracias @SofiaYYQ ya me estaba poniendo nervioso pensando que era para esta semana JAJAJAJ😆

**Comment by SofiaYYQ** [comment]
Yaya, y yo, con todo lo que quedan y la presentación 😢 .

No sé si es mejor crear un issue nuevo diciendo de crear un test de e2e para el despliegue o reutilizar el que tenemos, porque es importante, sino el despliegue va a dar fallo.

**Comment by uo276406** [comment]
Lo puse en el issue #125, inetentaré terminarlo antes de mañana a ver si puedo dejar listo el despliegue de una vez por todas
