### ISSUE TITLE
Corrección: Diagramas de secuencia

### ISSUE THREAD

**Issue by uo276406** [Arquisoft/dede_es5a#58]
Mostrar la capa de base de datos, para mostrar esta capa de persistencia. ¡Ojo! **No poner flechas de retorno de la base de datos**. También mostrar la restapi como una interfaz (como webapp), no como una database. Evitar incongruencias con el login a la hora de añadir y eliminar productos. También eliminar la capa de servidor que no aporta nada.

**Comment by SofiaYYQ** [comment]
Debería reflejar lo que haya en bussiness context y technical context o al revés, es decir, un poco de sincronización.

**Comment by SofiaYYQ** [comment]
- [ ] Mostrar la capa de base de datos, para mostrar esta capa de persistencia. ¡Ojo! No poner flechas de retorno de la base de datos. 

- [ ] También mostrar la restapi como una interfaz (como webapp), no como una database. 

- [ ] Evitar incongruencias con el login a la hora de añadir y eliminar productos. 

- [ ] También eliminar la capa de servidor que no aporta nada.
