### ISSUE TITLE
Crear Script de creación de datos de prueba y mejorar el CRUD de productos

### ISSUE THREAD

**Issue by AlonsoA-hub** [Arquisoft/dede_es5a#71]
Hacer un script de creación para la BD para poder contar con información sobre la que trabajar.

**Comment by uo276406** [comment]
@AlonsoA-hub, @UO250825, @SofiaYYQ, @mariaurrutia97 Os paso un fichero de los datos que ya se encuentran en mongo. Por ahora solo son productos, pero iré haciendo el resto una vez termine el mos¡delo. Para que podais ver la estructura y hacer pruebas. En disponibility, lo he modelado con un Set (size : stock). Si haceis peticiones a la restapi deberían poder verse los productos del fichero.
[products.txt](https://github.com/Arquisoft/dede_es5a/files/8207361/products.txt)
