### ISSUE TITLE
Crear un sistema de roles para seguridad de accesos

### ISSUE THREAD

**Issue by uo276406** [Arquisoft/dede_es5a#74]
Se deberá tener un sistema de roles para restringir el acceso a determinados puntos de la aplicación: por ejemplo añadir/eliminar/actualizar un producto, un pedido o un usuario solo podrá el usuario administrador, el resto de usuarios no podrá acceder a estas direcciones.

**Comment by AlonsoA-hub** [comment]
Añadir también sistema de encriptación de contraseñas para los usuarios
