### ISSUE TITLE
Investigación de una API para calculo de costes de envío

### ISSUE THREAD

**Issue by uo276406** [Arquisoft/dede_es5a#82]
Se debe buscar información e intentar encontrar un servicio web que permita calcular costes de envío de un pedido de una dirección a otra (ambas direcciones destino y origen conocidas)

**Comment by SofiaYYQ** [comment]
Hace tiempo que busqué información sobre APIs para los envíos y encontré este que trae un plan gratuito: [EasyPost](https://www.easypost.com/docs/api/node#rates), parece que sí que trae algo de calcular precios, pero no me documenté mucho.😅 Lo cito por aquí, por si queréis echarle un vistazo.

**Comment by uo276406** [comment]
Perfecto!!! Gracias @SofiaYYQ intentare investigar esta y alguna otra para tener algo funcional antes de la semana que viene 😉

**Comment by UO250825** [comment]
Encontré también esta:
[Picker Express](https://www.pickerexpress.com/desarrollador/como-se-calcula-el-costo-de-entrega)

**Comment by UO250825** [comment]
[Correos](https://www.correos.es/es/es/empresas/ecommerce/refuerza-la-logistica-de-tu-ecommerce/integracion-api)

**Comment by uo276406** [comment]
@UO250825, guau!!!, muchas gracias. En cualquier caso tengo que preguntaros ahora en la reunión un par de cosas sobre como calcularlo. Porque según lo tengo ahora pensado el coste se calcula cuando el cliente genera el pedido. Pero estuve pensando en hacerlo para que este coste se vea antes de hacer el pedido como tal y que lo podais mostrar antes de darle al botón de comprar o generar pedido. Ahora lo hablamos!!! 😄

**Comment by UO250825** [comment]
Esto también puede ser útil:

[Maps API](https://docs.mapbox.com/#maps)

**Comment by UO250825** [comment]
@uo276406 Vale perfe

**Comment by uo276406** [comment]
@UO250825 @mariaurrutia97 @AlonsoA-hub Para los que esteis con el tema de obtener la dirección de Solid y tal. Para el cálculo de coste de envío (como lo estoy planteando) es necesario pasar una peteción post a http://localhost:5000/order/price, solo depende de la distancia al centro de distribución vaya que no depende del pedido. En el cuerpo poner lo siguiente:
![imagen](https://user-images.githubusercontent.com/79643267/160210672-c73c293c-5126-4fba-bb36-519982631fc2.png)
- numer: número de portal
- street: nomre de la calle
- city : ciudad
- country : país (las pruebas que hice lo puse en Inglés...)
- zipcode: códgo postal
Lo digo para que sepais más o menos los datos que se necesitan para calcular el coste vaya 😉
