### ISSUE TITLE
Investigación de la conexión a SOLID

### ISSUE THREAD

**Issue by SofiaYYQ** [Arquisoft/dede_es5a#99]

**Comment by UO250825** [comment]
https://github.com/solid/react-components

**Comment by UO250825** [comment]
https://github.com/pglez82/solid-react-example

**Comment by UO250825** [comment]
https://docs.inrupt.com/developer-tools/api/javascript/solid-client-authn-browser/

**Comment by UO250825** [comment]
https://docs.inrupt.com/

**Comment by UO250825** [comment]
https://github.com/inrupt/solid-ui-react
